spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.bmclwyckvsywscextvxo
spring.datasource.password=Neiva$Solidaria2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html